name: Python Library CI

on:
  push:
    branches:
      - main  # Adjust the branch name as per your repository

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a requirements file

    - name: Run tests
      run: |
        pip install .
        pytest  # Assuming you're using pytest for testing
